# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/andre/test_env2/test_env2.cache/wt [current_project]
set_property parent.project_path C:/Users/andre/test_env2/test_env2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/andre/test_env2/test_env2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/imports/new/Reg_file.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/new/UC.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/imports/new/SSD.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/imports/new/MPG.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/new/MEM.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/new/IF_FETCH.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/new/EX.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/new/ID.vhd
  C:/Users/andre/test_env2/test_env2.srcs/sources_1/new/test_env2.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/andre/test_env2/test_env2.srcs/constrs_1/imports/new/basys3.xdc
set_property used_in_implementation false [get_files C:/Users/andre/test_env2/test_env2.srcs/constrs_1/imports/new/basys3.xdc]


synth_design -top test_env2 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env2.dcp

catch { report_utilization -file test_env2_utilization_synth.rpt -pb test_env2_utilization_synth.pb }
